intel/tinycbor

Makefile, Makefile.nmake
Just a few quick fixes.
@erichkeane, @dantler, @lpereira
=> Buildsystem update

src/compilersupport_p.h
=> Silence the annoying warning in MSVC about undeclared bswap

README
Update readme to properly use the 'intel.github.io' doc page.
=> Update documentation link in README

Makefile
- Enable BUILD_STATIC by default
- If BUILD_STATIC and BUILD_SHARED are both different from 1, return an
error
- If BUILD_STATIC is disabled, use shared library for binaries
- If both are enabled, use the static library
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> Add BUILD_STATIC option

tests/encoder/tst_encoder.cpp
Since Qt 5.9 has qfloat16, it became easier to write values. There was
no point with just the stand-in type, since the encoder would write
exactly the bytes we gave it.
=> Add support for more half-float values

src/cborparser.c
There was a section of code that was mostly the same, dealing with the
possibility of reading a Break (0xFF) as the next element in a map or
array. The only difference was that preparse_next_value() also
decremented the item count for the current list.
We could have used that, but that would have meant a +1 on the list,
which in turn lowers the number of possible elements from UINT32_MAX-1
to UINT32_MAX-2. Not a big deal, but we can avoid it by just splitting
to a new function and retaining tail-call optimisations.
=> Parser: merge the break-handling code in enter_container()

Makefile
=> Make it easier to build only the freestanding code

src/cborpretty.c
Adds ifdefs around the float handling to return an CborErrorUnknownType
if compiled without floating point support.
Instead of aborting with an error, it might be better to print a fixed string to indicate that there is a float, but that tinycbor is unable to decode it.
Signed-off-by: Koen Zandberg <koen@bergzand.net>
=> pretty: Add ifdefs for float support

.appveyor.yml
Avoid AppVeyor log cluttering by unittest progress messages
=> Make AppVeyor test suit run silent as in Travis

src/cborencoder.c
There is a minor error in the example code, that i noticed when trying using tinycbor.
=> Fixed minor error in the example code.

src/cborencoder.c
Exchanged function documentation of cbor_encode_text_string and cbor_encode_byte_string.
=> Encoder: Update documentation

examples/simplereader.c, src/cbortojson.c
This PR adds some checks for memory allocation failures in core library and example file
=> Add checks for memory allocation failures

src/cbor.h, src/cborencoder.c
as the names were unclear. containerEncoder could be the containing Encoder (that is, the one around the other thing)
I was confused as to which argument did which thing.
This helped me.
=> change the argument name from "encoder" to "parentEncoder"

examples/simplereader.c
Improve simplereader example to provide more convenient output.
=> Simplereader example minor improvements

.travis.yml
Only build docs if branch is "master"
=> Travis docs fix #196

tools/cbordump/cbordump.c
Hello,
I found a small misspelling while reading the code. Feel free to fix it either by merging this Pull Request or by adding a commit directly (if for example you found other misspellings).
=> Tools: fix JSON misspelling in cbordump

.appveyor.yml
Looks like AppVeyor dropped support for v6.1 QT as shown in https://www.appveyor.com/docs/windows-images-software/
Update to latest QT version
=> Update .appveyor.yml from QT v6.1 --> v6.5

.appveyor.yml, src/cbor.h, src/cborencoder.c, tests/encoder/tst_encoder.cpp, tests/parser/data.cpp, tests/parser/tst_parser.cpp, tests/tojson/tst_tojson.cpp
=> Cherry-pick dev branch content into main

src/cborencoder.c, src/cborencoder_close_container_checked.c, src/cborencoder_float.c, src/cborinternalmacros_p.h, src/cborparser.c, src/cborparser_dup_string.c, src/cborpretty.c, src/cbortojson.c, src/cborvalidation.c
Avoids having to repeat ourselves.
=> Move the source-selection macros to a common header

CMakeLists.txt
=> fix installdir in cmake build
