src/cbor.h

This calculates the length of a text string to be encoded using
strlen().  Useful when encoding constant strings.

Add convenience function cbor_encode_text_stringz()

---

src/cbor.h

floats and double are too big for value->extra and the
CborIteratorFlag_IntegerValueTooLarge flag is always set (see
cborparser.c:174). So there's no point in checking for the flag and we
can instead go straight to the internal function.

Micro-optimise cbor_value_get_{float,double}

---

src/cbor.h
src/cborencoder.c

When we wrote:
encoder->end = encoder->ptr = NULL;
}
++encoder->ptr;
We're incrementing a null pointer. This could be considered undefined
behaviour and the compiler would be free to remove the increment.
This commit solves that by using an integer called bytes_needed to store
the number of bytes needed.
The trick is, however, that this commit is actually a no-op: the new
member occupies the same storage as ptr and in all of the new
conditionals, both branches evaluate to the same code, so the
conditional can be removed.
The code is complex like this to ensure we don't run afoul of another
undefined behaviour: reading from a member of an union that was not the
last written to.
CID: 306167

Don't tempt undefined behaviour in incrementing null pointers

---

Makefile
src/cbor.h
src/cborencoder.c
src/cborencoder_close_container_checked.c
src/cborerrorstrings.c
src/cborparser.c
src/compilersupport_p.h
src/extract_number_p.h
src/src.pri
tests/encoder/tst_encoder.cpp

This fixes issue #4. The code is placed in a new file and function so
that only people who need it will pay the cost of this function. The
impact to existing code is minimal.
Before:
text    data     bss     dec     hex filename
945       0       0     945     3b1 cborencoder.o
2743       0       0    2743     ab7 cborparser.o
After:
1060       0       0    1060     424 cborencoder.o
2756       0       0    2756     ac4 cborparser.o

Implement checking of array and map sizes

---

src/cborparser.c
src/extract_number_p.h
tests/parser/tst_parser.cpp

If the size of the string was a suitable value, the "ptr + total" check
could overflow and we wouldn't know because the sum would most likely be
smaller than value->parser->end. We would then proceed to allocate a
silly amount of memory.
I never caught this in my own testing because, on Linux, the heap
usually starts in the low 4 GB of the address space, so adding
0xffffffff000000000 would not cause an overflow. However, on OS X, the
heap starts above 4 GB, so the pointer does wrap around.
So test specifically for the pointer wraparound cases, plus the case of
sizes larger than the address space in 32-bit systems.

Fix a parsing issue caused by pointer wraparounds

---

Makefile.nmake
src/cbor.h
src/cbortojson.c
src/compilersupport_p.h
tests/.gitignore
tests/encoder/encoder.pro
tests/encoder/tst_encoder.cpp
tests/parser/parser.pro
tests/parser/tst_parser.cpp
tests/tests.pro
tests/tojson/tojson.pro

This series of commits fixes the build and makes the parser and encoder tests pass with MSVC.
The to and from JSON functionality is not enabled with MSVC.
@dantler, @dthaler

Fix build msvc

---

Makefile
Makefile.nmake
maketag.pl

The previous part of the Makefile didn't work properly. Instead of using
the contents of the VERSION file, it updated the file right before the
tagging and always for the next minor release.
Instead, move everything to a Perl script that updates the VERSION file
only after the tagging and sets up for a patch release (which are more
frequent). Updating of the dev branch is left as an exercise for the
reader.
As a bonus, this will work on Windows too without Unix shell tools.

Create a Perl script that properly creates tags

---

src/cborparser.c

This removes an ugly cast from the source and an unnecessary 1-byte
variable from the .rodata section.

Don't cast an actual string literal to uint8_t*

---

Makefile

json2cbor depends on cjson so tools/json2cbor/json2cbor.o must be
before -lcjson
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

Fix static compilation of json2cbor

---

src/cbor.h
src/cborparser.c
src/cborparser_dup_string.c
tests/parser/tst_parser.cpp

This is a new v0.5 feature: the ability to parse chunked CBOR strings per chunk. It also adds the ability to do zero-copy parsing of strings. From the docs:
```c
if (cbor_value_is_text_string(value)) {
char *ptr;
size_t len;
while (1) {
err = cbor_value_get_text_string(value, &ptr, &len, &value));
if (err) return err;
if (ptr == NULL) return CborNoError;
consume(ptr, len);
}
}
```
There are two commits in this series:
1. Add support for parsing chunked strings
2. rewrite the iterate_string_chunks function with new chunk code

Chunked string parsing

---

src/cbor.h
src/cborinternal_p.h
src/cborparser.c
src/cborpretty.c
tests/parser/tst_parser.cpp

This branch extends the cbor_value_to_pretty API with a new enum and updates the documentation. As a consequence, we can now match the RFC 7049 recommendations, even if the default settings remain as they were in previous TinyCBOR versions.
```c
enum CborPrettyFlags {
CborPrettyNumericEncodingIndicators     = 0x01,
CborPrettyTextualEncodingIndicators     = 0,
CborPrettyIndicateIndetermineLength     = 0x02,
CborPrettyIndicateOverlongNumbers       = 0x04,
CborPrettyShowStringFragments           = 0x100,
CborPrettyMergeStringFragments          = 0,
CborPrettyDefaultFlags          = CborPrettyIndicateIndetermineLength
};
```

More detailed cbordump

---

src/cbor.h

Hide the API using FILE* from freestanding C implementations

---

src/compilersupport_p.h

Recent GCC have begun complaining about it. The buildsystem should do
this, not a header.
compilersupport_p.h:175:11: warning: bad option '-ffunction-sections' to pragma 'optimize' [-Wpragmas]

Remove the #pragma for -ffunctions-sections

---

Makefile

Some people may want to use tinycbor as a shared library instead of
as a static library, so providing a set of .so accordingly.
Even with the static library, I'm having trouble incorporating it
into another shared library, so providing -fPIC option as well.
Signed-off-by: Bertrand Roussel <broussel@sierrawireless.com>

Provide shared library

---

Makefile.nmake

Fix MSVC build: cborvalidation.obj wasn't added to the library

---

tools/json2cbor/json2cbor.c

Observed issue on earlier version:
json2cbor.c:157:5: \
error: for loop initial declarations are only allowed in C99 mode
Note, it's not manatory for current master branch
since build script already sets the c99 flag,
but it won't cause any harm.
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

json2cbor: Initialize index before "for scope"

---

Makefile

Detect if this is an ELF system by checking if /bin/sh is ELF. This can
be configured manually with:
make BUILD_SHARED=0
or
make BUILD_SHARED=1

Fix build on non-ELF systems (macOS): don't build the shared library

---

Makefile

We were leaving the .pic.o files behind
@CoRfr

Make sure that -fPIC objects are removed in make clean

---

src/cborencoder.c
src/cborparser.c
src/cborparser_dup_string.c

- The defines(_BSD_SOURCE, _DEFAULT_SOURCE) were getting defined in multiple source files 
generating warnings
- Solution is to conditionally define the above
- These were seen when making changes for [Tinycbor mynewt upstream #83](https://github.com/intel/tinycbor/pull/83)
```
9.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.9.2/lib -o tst_cpp.o tst_cpp.cpp
In file included from tst_cpp.cpp:27:
./../../src/cborencoder.c:25:9: warning: '_BSD_SOURCE' macro redefined [-Wmacro-redefined]
#define _BSD_SOURCE 1
^
../../src/compilersupport_p.h:35:11: note: previous definition is here
^
In file included from tst_cpp.cpp:27:
./../../src/cborencoder.c:26:9: warning: '_DEFAULT_SOURCE' macro redefined [-Wmacro-redefined]
#define _DEFAULT_SOURCE 1
^
../../src/compilersupport_p.h:38:11: note: previous …
```

Fix compiler warnings for tst_cpp

---

src/cborparser.c

This allows advance_recursive to be called with different levels when
called directly.

Invert the way we account for the recursion level

---

src/cborencoder.c
tests/encoder/tst_encoder.cpp

Conditional added by 3369dd1f017598f74c3f6f36591505377d72bd9d was
inverted.

Encoder: Fix the returning of OOM errors in closing containers

---

src/cborinternal_p.h
src/cborparser.c
src/cborpretty.c

The pretty-dumper code did not have a limit, assuming that the input had
been validated beforehand, so if the nesting was too deep, one would
have got an error before getting to the dumper.
However, it's not inconceivable that someone adds a logger code to a
packet a bit too early. So let's be defensive and apply the limiter here
too.

Pretty: limit the number of recursions, like the Parser

---

src/cborvalidation.c
tests/cpp/tst_cpp.cpp

Like the rest of our parser and encoder, it's useful to be #include'd in
C++ souces.

Validation: make sure that it compiles in C++ mode too

---

src/utf8_p.h

Add #include guards to the utf8_p.h internal header

---

src/cbor.h
src/compilersupport_p.h

The C standard requires every the macro to be redefined every time that
<assert.h> is included. It does so you can change NDEBUG from one
But that also means a wrapper couldn't #define assert to their own
macro. So stop overriding.

Only #include <assert.h> if assert isn't yet defined

---

src/cborparser.c

Probably a good idea anyway, plus solves a false positive warning:
```
src/compilersupport_p.h:192:34: error: ‘chunkLen’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
return __builtin_add_overflow(v1, v2, r);
~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
src/cborparser.c:1163:16: note: ‘chunkLen’ was declared here
size_t chunkLen = chunkLen;
^~~~~~~~
```

Parser: set *len = 0 in the last string chunk

---

tests/encoder/tst_encoder.cpp
tests/parser/tst_parser.cpp

Some QCOMPARE did convert to int() so we would see an error number, but
not all comparisons did. For those those that didn't, QCOMPARE would
just print that the values differed, but not show what.
So try to harmonize on printing the error message.
I may not have caught all uses...

Tests: print the error message insead of just a number (or nothing)

---

src/cborvalidation.c

GCC7 complains, though it's wrong:
```
src/cborvalidation.c:472:57: error: ‘previous’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
src/cborvalidation.c:485:61: error: ‘previous_end’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

Valiation: suppress warning about uninitialized variables

---

src/cbor.h
src/cborencoder.c
src/cborencoder_close_container_checked.c
tests/encoder/tst_encoder.cpp

Instead of counting forward the number of items added, which meant we
couldn't know in cbot_encoder_close_container() whether we had added
enough, let's count backwards. The number is offset by 1 so we should be
at 1 if we added exactly as many items as we had expected to. Zero means
we added too many. Any other number means we added too few.

Encoder: Change the way we reckon the number of items added

---

src/cbor.h

This gives us a little more room to add validation errors when we have
to keep binary compatibility.

JSON: Change the first number of the JSON conversion errors

---

src/cborencoder.c
tests/encoder/tst_encoder.cpp
tests/parser/tst_parser.cpp

The documentation said we encoded the negative value equivalent to the
passed absolute value. That means encode_number() requires the
subtraction.
This commit takes the opportunity to unit-test the rest of the integer
API in the parser.

Encoder: Fix off-by-one error encoding negative numbers

---

src/cbor.h
src/cborpretty.c
tests/parser/tst_parser.cpp
tools/cbordump/cbordump.c

Will keep the misspelt name for a few releases and remove later.

Pretty: fix typo in enum name

---

tests/encoder/tst_encoder.cpp

The `compareFailed` variable was never initialised or set to anything.

Tests: fix the checking if the current test failed

---

src/cbortojson.c

CborToJson: fix memory leak in case fprintf fails

---

tools/json2cbor/json2cbor.c

perror() doesn't exist. It's not like Perl's die().

json2cbor: don't crash if realloc() returns false

---

src/cbor.h
src/cborinternal_p.h
src/cborparser.c
tests/parser/tst_parser.cpp

This reverts commit 6587c3e1d25670d2da2514a6f1261dd409c854f0. Bringing
the API back in 0.6, but it'll change before the release.

Revert "Parser: remove the cbor_value_get_xxxx_string_chunk() API"

---

src/cborvalidation.c

We don't need to compare the map lengths directly. The memcmp is
sufficient, since the source data is big endian.
Of course, verifying for sorting requires the map has known length.

Validator: simplify (and correct) the map sorting verification

---

src/cborinternal_p.h
src/cborparser.c

Visual Studio expects the __fastcall attribute
between return type and function name.
Signed-off-by: Andreas Zisowsky <zisowsky@lynxtechnology.com>

Fix compile error on Windows x86.

---

Makefile

Fixes https://github.com/intel/tinycbor/issues/120

Update gcc flags to enable building json2cbor with gcc 4.4.7 (standard in CentOS 6)

---

src/cborvalidation.c

Compiling without floating point support causes compilation errors due to a missing closing brace in the case statement. This PR fixes that by moving the closing brace outside the `#ifdef`

validation: Fix brace mismatch with float disabled

---

src/cbor.h
src/cborparser.c
src/cborvalidation.c

On architectures where `int` is 16 bits wide (AVR/arduino) gcc complains about possible overflow caused by the parser validation flags.
This PR changes the flag argument when used for the validation flags to uint32_t so that the enum doesn't cause overflows on any architecture.
I hope I didn't miss any places where the data type has to be changed :)

Change flag type to uint32_t for parser validation flags

---

src/compilersupport_p.h

Suggested in https://sourceforge.net/p/predef/wiki/Endianness/ and also
found by looking into glibc's <endian.h>. Plus some recommendation from
other people.
This fixed the build on INTEGRITY.

Add more byte order detection code

---

src/cborvalidation.c

As the subject indicates, cborvalidation.c fails to compile when `CBOR_NO_HALF_FLOAT_TYPE` is defined due to a variable name mismatch.
Signed-off-by: Koen Zandberg <koen@bergzand.net>

validation: fix undef var with half float disabled

---

.travis.yml
Makefile
Makefile.configure
src/cborinternal_p.h
src/cborpretty.c
src/cbortojson.c
src/compilersupport_p.h

This commit series fixes TinyCBOR building in both freestanding and no-floating-point environments, adding testing in Travis for those two cases.
@georgen117 @lpereira

Fix no-FP builds

---

src/utf8_p.h
tests/parser/tst_parser.cpp

I ported this from code I had written for Qt, where the subtraction was
correct. Qt's code is roughly:
```
uchar b = *src++;
...
int bytesAvailable = Traits::availableBytes(src, end);
if (Q_UNLIKELY(bytesAvailable < charsNeeded - 1)) {
```
Which means src was advanced by the time we call Traits::availableBytes,
meaning that call returns the number of continuation bytes only. Our
code was:
```
ptrdiff_t n = end - *buffer;
...
uc = *(*buffer)++;
...
if (n < charsNeeded - 1)
```
Which means our n is the total number of bytes, including the first
byte.

Fix #137: off-by-one error in UTF-8 decoding

---

tools/json2cbor/json2cbor.c

encode_half has been moved from compilersupport_p.h to cborinternal_p.h
in commit bfc40dcf909f1998d7760c2bc0e1409979d3c8cb so include this file
in json2cbor to avoid the following build failure:
/home/buildroot/autobuild/run/instance-0/output/host/bin/microblazeel-linux-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I./src -std=gnu99 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os    -c -o tools/json2cbor/json2cbor.o tools/json2cbor/json2cbor.c
tools/json2cbor/json2cbor.c: In function 'decode_json_with_metadata':
tools/json2cbor/json2cbor.c:295:50: warning: implicit declaration of function 'encode_half' [-Wimplicit-function-declaration]
(half = encode_half(v), cbor_encode_half_float(encoder, &half));
^~~~~~~~~~~ …

fix undefined encode_half in json2cbor

---

examples/simplereader.c

should be CborError rather than bool

typo in dumprecursive return type

---

Makefile

Misleading warning `warning: funopen and fopencookie unavailable, open_memstream can not be implemented and conversion to JSON will not work properly!` is issued when configuring project first time.

eliminating misleading messages during project build in case .config file not yet created

---

src/cborpretty.c
src/cborvalidation.c
tests/parser/tst_parser.cpp

We can only validate_number() if we know that we have a number to
validate in the first place. If we've reached the end of our string, the
content that follows is not necessarily a number (it could be a Break
byte). More importantly, we could reach the end of the buffer.
This issue was masked by the way we provided data to the parser. It
always came from read-only memory becausee of QByteArray::fromRawData(),
so valgrind never caught any issues. Using QByteArray directly wouldn't
have helped because it always inserts a terminating null byte, which
always validates as a correct number (unsigned 0) and fails to trigger
valgrind.
So we need to use malloc() directly to make Valgrind complain. And there
was already a test that did:
==26543== Invalid read of size 1
==26543==    at 0x483EA10: …

Validation: fix out-of-bounds access when content ends in a string

---

tests/encoder/tst_encoder.cpp

Tests: Catch an earlier QCOMPARE failure in compare()

---

src/cborencoder.c

Fixed the error checking example proposed in the comments/documentation at the beginning of the file.
Changed occurrences of `if(!err)` to `if(err)`, and `cbor_assert(err)` to `cbor_assert(!err)`.

Update cborencoder.c documentation

---

src/cbor.h
src/cborparser.c
tests/parser/tst_parser.cpp

If a map end (Break byte) occurs before we've read the concrete item for
the value, then the map is invalid.
Fixes #167

Parser: validate that maps have both key and value items

---

src/cbortojson.c
src/compilersupport_p.h

cbortojson.c
Fix warning: initialization discards 'const' qualifier from pointer target type
compilersupport_p.h 
Fix warning: __cplusplus / __cpp_static_assert is not defined …

Fix compilation warnings

---

src/open_memstream.c

The open_memstream.c is using GLIBC macro definition to test if the library is building on a Linux box. This makes it impossible to build tinycbor against other C libraries, as musl for example. This can be tested using an alpine docker image.

Enable build for different c libraries

---

src/cborencoder.c

I was getting the following error when compiling cborencoder.c as part of
QtBase for FreeBSD MIPS64:
error: explicitly assigning value of variable of type 'uint64_t' (aka 'unsigned long') to itself [-Werror,-Wself-assign]
v = cbor_htonll(v);

Fix -Werror,-Wself-assign on big-endian systems

---

src/cborencoder.c

When a container is closed, the outer container's buffer state is
synchronised with the inner container's state.
This was previously done via:
```
CborError cbor_encoder_close_container(CborEncoder *encoder, const CborEncoder *containerEncoder)
{
if (encoder->end)
encoder->data.ptr = containerEncoder->data.ptr;
else
encoder->data.bytes_needed = containerEncoder->data.bytes_needed;
encoder->end = containerEncoder->end;
...
return CborNoError;
}
```
However, strictly speaking the inner container could have updated `end` to be `NULL` if
the buffer was too small. In that case, the outer container should carry over `bytes_needed`
and not `ptr`. However, the logic was using the outer container's "stale" view of `end`.
However, generally `sizeof(ptr)` and `sizeof(bytes_needed)` are the same, and …

Refine handling of container state synchronisation

---

Makefile

GNU install makes a file at the destination if you set the source to a link. This fixes multiply-installed libraries in `/usr/lib` when running `make install`.

Fix links to shared library upon "make install"

---

.appveyor.yml
src/cborinternal_p.h

MSVC (and I think ICC too) are lacking the simpler, scalar instructions
to convert from single-precision to half-precision and back. Instead, we
need to use the packed data intrinsics.
Fixes #192.

cborinternal_p.h: Fix AVX2 build with MSVC

---

tests/parser/tst_parser.cpp

Or don't terminate, as the case may be.
Relates to #194.

parser: add a test that the string copy functions properly terminate

---

src/cborencoder.c

Another interpretation is that the library will guess the number of items and back-patch the length.
(It won't, but it's good to say so)

clarify that CborIndefiniteLength creates an indefinite map.

---

src/cbor.h
src/cborencoder.c
src/cborparser.c
tests/parser/tst_parser.cpp

This method allows for writing raw data directly to the encoding buffer. Particularly useful if you have something stored as CBOR encoded data and want to push it to your encoding stream/buffer.

Added the method cbor_encode_raw to the API

---

Makefile
Makefile.configure

The project makefile uses fd 9 to redirect output, when generating the contents of the `.config` file. Previously, it used fd 10, but was changed due to compatibility concerns (https://github.com/intel/tinycbor/commit/c88913e53c7aeda47cdaa8947949af29f48697ff).
The build fails in environments where this file descriptor can't be used. I've encountered this error trying to build `tinycbor` as part of a dependency, from a Cargo crate build script which invokes `make` ([see logs](https://github.com/AlfioEmanueleFresta/xdg-credentials-portal/runs/3776889537#step:5:283)):
```
make[2]: *** read jobs pipe: Bad file descriptor.  Stop.
make[2]: *** Waiting for unfinished jobs....
/bin/sh: 1: 9: Bad file descriptor
```
Proposing a fix, changing the `OUT` variable to take a path to append to, instead …

Makefile: Use file name instead of file descriptor for .config target

---

Makefile

Allow the user to disable `-Werror` to avoid the following build failure with gcc 4.8 raised since version 0.6.0 and https://github.com/intel/tinycbor/commit/e2a4ed135c4d9101c4df83f2dd033cd249b6ef07:
```
/home/buildroot/autobuild/instance-1/output-1/host/bin/arm-none-linux-gnueabi-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I./src -std=gnu99 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g0 -D_FORTIFY_SOURCE=1 -Werror=incompatible-pointer-types -Werror=implicit-function-declaration -Werror=int-conversion -fPIC  -c -o src/cborerrorstrings.pic.o src/cborerrorstrings.c
cc1: error: -Werror=incompatible-pointer-types: no option -Wincompatible-pointer-types
cc1: error: -Werror=int-conversion: no option -Wint-conversion
```
Fixes:
- …

Makefile: add DISABLE_WERROR

---

Makefile

Because C allows this:
```c
void f(int *x);
void g(const int *x)
{ f(x); }
```

Makefile: add -Werror=discarded-qualifiers to the C flags

---

src/cborparser.c

This is undefined behaviour as caught by Xcode 13.2.1:
```
/Users/ham/TinyCborObjc/tinycbor/src/cborparser.c:1214:37: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/ham/TinyCborObjc/tinycbor/src/cborparser.c:1214:37 in 
```

If the buffer pointer is a null pointer then don't apply an offset to it

---

src/cborparser_dup_string.c

This PR is intended to address #75 
This change allows consumers to replace standard library memory management functions (`malloc` and `free`) with their own memory allocator functions without changing the tinycbor code. Since this seems most useful in an embedded context, this change is scoped to the **cborparser_dup_string.c** parser file only.
One goal of this update is to be fully backward compatible with existing code. Current consumers of this library who want to continue to use the standard library memory management functions do not need to make any changes to their code or project configuration.
Consumers who want to replace `malloc` and `free` should create a header file that defines `cbor_malloc` and `cbor_free`. Then, they set this header file as the value of the …

Facilitate replacement of standard library memory management functions

---

src/cborpretty.c

Using `cbordump` on the enclosed input fails with an assertion error :
```
cbordump: src/cborparser.c:633: cbor_value_leave_container: Assertion `recursed->type == CborInvalidType' failed.
```
The problem is the following : there is an implicit assumption when quitting `container_to_pretty` that the iterator is advanced to its end. This assumption is broken whenever we reach the recursion limit.
The failing input was found by @niooss-ledger.
[max-recurse-limit-fail-input.txt](https://github.com/intel/tinycbor/files/10725330/max-recurse-limit-fail-input.txt)

cborpretty: fix assertion failure if recursion limit was hit

---

src/cborencoder.c
src/cborencoder_close_container_checked.c
src/cborencoder_float.c
src/cborinternal_p.h
src/cborparser.c
src/cborparser_dup_string.c
src/cborparser_float.c
src/cborpretty.c
src/cbortojson.c
src/cborvalidation.c
tools/json2cbor/json2cbor.c

Implement support for half-precision floating-point conversions using `_Float16` introduced in C11 extension ISO/IEC TS 18661-3.
Recent ARM compilers support _Float16.

Use _Float16 for half conversions if available

---

src/cbor.h

Currently I am working on a project where I have to define CBOR_PARSER_ADVANCE_BYTES_FUNCTION and CBOR_PARSER_TRANSFER_STRING_FUNCTION macros. Unfortunately the library doesn't include any external config file and building system I am using provides only possibility to add simple preprocessor definitions (like definition = value) on building script level. Adding macros is not possible. For this reason I am asking if we can add above change - if I add simple definition CBOR_EXTERNAL_CFG by build system then cbor will require cbor_cfg.h file where I can add needed macros.

Added possibility to include external config file.

---

tests/encoder/data.cpp
tests/parser/data.cpp

The Qt uses test batching and potentially encoder/data.cpp and parser/data.cpp can end up in the same translation unit. This can be problematic as they declare symbols with the same names.
Change both files to use internal linkage in order to avoid symbols clashing.

Use internal linkage for data.cpp files

---

src/cborencoder.c
src/cborparser.c
src/cborparser_dup_string.c

The \c and \b commands accept a single word,
and there are no \section1 or \list commands
according to the Doxygen manual.

Fix Doxygen warnings

---

src/cborparser_dup_string.c
src/cbortojson.c
src/memory.h

facilitate replacement of malloc/free functions
open_memstream functions are left out of this change as they require other functions from stdlib.

follow-up commit to 75eaa19

---

src/compilersupport_p.h

Follow the same "pattern" as for the rest of the #if directive: first test if a macro is defined, then test the value. Otherwise the code triggers a -Wundef warning (e.g. when building in C++).

Prevent a -Wundef warning

---

examples/simplereader.c

When compiling `simplereader.c`, following error is generated.
```
simplereader.c: In function ‘main’:
simplereader.c:181:19: error: ‘CborValue’ has no member named ‘ptr’
181 |                 it.ptr - buf, cbor_error_string(err));
|                   ^
```
As shown below, member of `struct CborParser` has been slightly changed in commit [34c8452](https://github.com/intel/tinycbor/commit/34c84520a764dfe5bac6725aa95e9871baf0bbc6)
```diff
struct CborValue
{
const CborParser *parser;
-    const uint8_t *ptr;
+    union {
+        const uint8_t *ptr;
+        void *token;
+    } source;
uint32_t remaining;
uint16_t extra;
uint8_t type;
@@ -298,13 +319,14 @@ typedef struct CborValue CborValue;
```
Therefore, replacing `it.ptr` with `it.source.ptr` will fix the error.

Corrected syntax error in `examples/simplereader.c`

---

.appveyor.yml

AppVeyor: replace Qt 5.13+MSVC 2017 with Qt 6.8+MSVC 2022

---

src/cborparser.c
src/compilersupport_p.h

The `/* fallthrough */` comment isn't always handled, causing some compilers to complain about falling through.

compilersupport_p.h: add a macro for the fallthrough attribute

---

tests/parser/tst_parser.cpp

`Q_ASSERT()` disappears in release mode, leading Clang to print a static analysis warning about an impossible condition:
```
tst_parser.cpp:251:16: warning: variable 'err' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
251 |     } else if (ourType == CborTextStringType) {
|                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tst_parser.cpp:263:12: note: uninitialized use occurs here
263 |     return err;
|            ^~~
tst_parser.cpp:251:12: note: remove the 'if' if its condition is always true
```
`Q_UNREACHABLE()` becomes a plain `__builtin_unreachable()` in release mode.

tst_Parser: replace Q_ASSERT(false) with Q_UNREACHABLE()

---

src/cborencoder.c
src/compilersupport_p.h

Coverity complains that, when CBOR_ENCODER_WRITE_FUNCTION is defined, enc.data is read in cbor_encoder_create_map() when cbor_encoder_init_writer() didn't write to it.
While 'data' is merely copied in cbor_encoder_create_map(), Coverity is right, though: reading an uninitialized value is UB.
Fix by setting data.writer to nullptr (abstracting the difference between C and C++ behind a new macro).

Always init CborEncoder::data in cbor_encoder_init_writer()

---

src/cbortojson.c
tests/tojson/tst_tojson.cpp

1024 levels will probably be good enough for everyone, like cborparser.c. For those for whom it isn't, they can set the limit during the build.
We already had this for the plain parser, so TinyCBOR wouldn't cause a stack overflow in case of a malformed stream (intentionally or not) when simply parsing and advancing over the stream. This same protection wasn't applied to the content converting from CBOR to JSON.

CBOR-to-JSON: Limit how deep we process nested containers

---

src/cbortojson.c
src/compilersupport_p.h
src/memory.h
tests/tojson/tst_tojson.cpp

We hadn't bothered, as this was just example-like code to show how one could convert from CBOR to JSON. But as it was added to the library (no extra dependency), we should Do The Right Thing (DTRT) and escape.
This patch could have used `cbor_value_to_pretty()` to print the string, which has better support for UTF-8 escaping and thus checks for UTF-8 correctness, but that would make `map_to_json()`'s metadata functionality much more complex, especially since we cannot rely on `open_memstream()` always being available. Therefore, we are partially duplicating cborpretty.c's `utf8EscapedDump()`.

CBOR-to-JSON: do properly escape JSON strings

---

tools/json2cbor/json2cbor.c

There's a discussion in the C and C++ communities whether you're allowed to use the values of pointers that have been deallocated, if you don't dereference them. Some argue that it is Undefined Behaviour in spite of the numeric value stored in the variable not having changed.
Instead of arguing, let's just make sure we don't use the pointers after they have become dangling. We only needed the offset of how far we've written into the buffer to restore the state and we have a function that returns exactly that.
Seen while debugging #259.

json2cbor: don't use the buffer variable after realloc()

---

src/cborparser_dup_string.c

We were returning from the function with the memory we had allocated and freed, if the second iteration over the string produced a failure that didn't happen on the first one. This can't happen with pure memory buffers, but can happen with an external data source that fails to produce the same contents twice.
I'm documenting that the values in all error conditions except for OOM are undefined, so one mustn't attempt to use them, even to free. This does not change behaviour of the library, just documents.
But this commit does make it clear the OOM condition will return a valid `*buflen` and `next`, the latter of which is new behaviour with this commit.
Fixes #258.

cborparser_dup_string: don't modify *buffer until success

---

CMakeLists.txt
Makefile
Makefile.nmake
cmake/PackageConfig.cmake
cmake/project-config.cmake.in
src/cbor.h
src/tinycbor-export.h.in
tests/CMakeLists.txt

This PR adds [CMake](https://cmake.org/) support to build and install the library and CMake export package.

Add CMake support

---

src/cbortojson.c

Both the C and C++ standards say it is Undefined Behavior to convert a floating point number to integer if the input is out of bounds of the destination type.
And indeed this started failing in recent builds, with
val = 18446744073709551616  (2^64)
it has probably been producing ival = 18446744073709551615 for a while, but the conversion back to floating point now rounded up and compared equal to the input.
So let's just fix it.

CBOR-to-JSON: fix UB in converting out-of-bounds FP to integer

---

src/cbortojson.c

When function `text_string_to_escaped successfully` parses a string and fails to parse the next value (`cbor_value_finish_string_iteration` returns an error), it correctly propagates the error but the string is never freed.
This can be reproduced with:
```sh
make CC='clang -g -fsanitize=address'
printf '\x82\x60\xff' | ./bin/cbordump -j
```
clang's Address Sanitizer reports:
=================================================================
==20317==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 1 byte(s) in 1 object(s) allocated from:
#0 0x560b654b9916 in __interceptor_realloc (/tinycbor/bin/cbordump+0xa4916) (BuildId: f9933666b5d987b21f68c2887de4aebe93bc2bef)
#1 0x560b654f5c18 in escape_text_string /tinycbor/src/cbortojson.c:331:15
#2 0x560b654f3e29 in text_string_to_escaped …

CBOR-to-JSON: fix memory leak when parsing invalid CBOR

---

src/cbortojson.c

Use `add_check_overflow` and `mul_check_overflow` to ensure the arithmetic operations do not overflow when computing the size to allocate.

CBOR-to-JSON: fix integer overflow when computing allocation size

---

src/cborpretty.c

When printing CBOR data containing NaN, function `convertToUint64` does an undefined behavior. This can be reproduced using test cases from `tests/parser/data.cpp`:
```console
$ make CC='clang -fsanitize=undefined'
$ printf "\xfb\x7f\xf8\0\0\0\0\0\0" | ./bin/cbordump
src/cborpretty.c:171:17: runtime error: nan is outside the range of representable values of type 'unsigned long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/cborpretty.c:171:17 in
nan
$ printf "\xf9\x7e\x00" | ./bin/cbordump
src/cborpretty.c:171:17: runtime error: nan is outside the range of representable values of type 'unsigned long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/cborpretty.c:171:17 in
nan
```
Fix this by checking whether the value to convert is not NaN.

Pretty: fix Undefined Behavior with NaN floats

---

src/cborpretty.c

When `value_to_pretty` is called with `recursionsLeft=0` and an Array or Map type, `container_to_pretty` is called with `recursionsLeft - 1 = -1`. This breaks the recursion limit check.
In practice, this can be triggered with a CBOR data containing 1023 Arrays, a Tag and many more Arrays:
```console
$ python3 -c 'import sys;sys.stdout.buffer.write(b"\x9f" * 1023 + b"\xc0\x9f" + b"\x9f" * 100000 + b"\xff" * 101024)' | ./bin/cbordump
Segmentation fault (core dumped)
```
This segmentation fault is due to the stack growing too much, due to the quantity of recursive calls.
Fix this by reporting a proper error instead. The same input now produces:
```text
[_ [_ [_ ... [_ 0([
-: internal error: too many nested containers found in recursive function
_ <nesting too deep, recursion stopped>
``` …

Pretty: ensure recursionsLeft is not zero before decrementing it

---

.appveyor.yml
.github/workflows/build.yml

This switches the GitHub Actions and AppVeyor CIs to using the CMake build instead of the old Makefile/qmake hybrid.
New features:
* Compiles with `-Wall -Wextra -Werror`
* Compiles using the Address Sanitizer on macOS
* Compiles the testing runs using shared libraries instead of static

CI: switch to using CMake

---

src/compilersupport_p.h

I think GCC says `__has_cpp_attribute(fallthrough)` is true because C++ supports it (it means "has C++ attribute"), but that doesn't apply to the C language. This causes a compilation error:
```
compilersupport_p.h:57:41: error: expected expression before '[' token
57 | #    define CBOR_FALLTHROUGH            [[fallthrough]]
|                                         ^
cborparser.c:225:13: note: in expansion of macro 'CBOR_FALLTHROUGH'
225 |             CBOR_FALLTHROUGH;
|             ^~~~~~~~~~~~~~~~
```
Instead, we should use the C23 `__has_c_attribute` to detect the C attribute.
Fixes #293.

Fix build with GCC < 11: [[fallthrough]] is supported but not allowed in C

---

CMakeLists.txt
cmake/PackageConfig.cmake

I changed CMakeLists.txt to enable `FetchContent` this library from the user library.
1. In the case of `cmake_source_dir`, there was an issue where it was overridden with the parent project path when building the library using `FetchContent`, causing it to not work properly. So I changed `cmake_source_dir` to `project_source_dir`.
2.  I remember the header install path is `tinycbor/cbor.h`, but has the installation path changed to `cbor.h`? If the `cbor.h` installation is only performed during the cmake install process, that part should also be fixed.

Fetchcontent frendly CMakeLists.txt

---

src/cborinternal_p.h

Commit 3cba6b1 ("Use _Float16 for half conversions if available") added support for using half-width float support in the compiler to perform encoding operations, using the FLT16_MANT_DIG macro to check for support on the given target.
However, on x86 GCC only supports this when SSE2 is enabled[1]. Unlike clang and the other architectures where support for this is conditional, GCC *does* define those macros even without SSE2 support, causing a build failure:
```
In file included from cborencoder_float.c:29:
cborinternal_p.h: In function ‘encode_half’:
cborinternal_p.h:56:5: error: invalid conversion to type ‘_Float16’ without option ‘-msse2’
56 |     _Float16 f = (_Float16)x;
|     ^~~~~~~~
cborinternal_p.h: In function ‘decode_half’:
cborinternal_p.h:65:5: error: invalid conversion from …
```

fix build on i386 without SSE2
